image: python:3.10

test:
    script:
        - apt update -yq
        - apt install -y python3-opencv
        - pip install setuptools pytest
        - pip install .
        - python -m pytest tests/

build-package:
    stage: deploy
    before_script:
        - python -m pip install --upgrade twine
        - python -m pip install --upgrade build
        - sed -i -e "s/version=.*$/version='$CI_COMMIT_TAG',/" setup.py
        - cat setup.py
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    script:
        - python -m build
        - python -m twine upload dist/*
    rules:
        - if: $PYPI_USERNAME
        - if: tags

