# ============================================================================
# Per-powder BH-loop logging for magnum.np -- READY-TO-PASTE version
# ============================================================================
# Two paste blocks:
#   BLOCK 1 goes into your script AFTER the usual setup, i.e. it needs these
#           names to exist already:
#             state     ... the State
#             demag     ... DemagField() or DemagFieldPBC() instance
#             external  ... ExternalField instance (the AC drive)
#             filter_L  ... indicator field of the large powder (see below)
#             filter_S  ... indicator field of the small powder
#   BLOCK 2 is four lines added INSIDE your existing time loop.
#
# The resulting data/loop.dat is evaluated with the standalone companion
# script evaluate_bh_loop.py (numpy only):
#     python evaluate_bh_loop.py data/loop.dat --period <cycle duration in s>
#
# Conventions:
# * All per-phase columns are PHASE-VOLUME averages: magnum.np's ScalarLogger
#   averages tensors over the WHOLE mesh (state.avg), so every filtered field
#   is divided by phi_i = avg(filter_i) here. Sanity check: |J_i| <= mu0*Ms_i
#   at all times, otherwise filters/normalisation are wrong.
# * The demag operator is linear in Ms*m, so the stray field generated by ONE
#   powder alone is obtained EXACTLY by evaluating demag.h with the other
#   phase's magnetisation masked to zero, and
#       h_demag == h_from_L + h_from_S   (up to float round-off).
#   A larger residual means the filters overlap or miss magnetic cells.


# ----------------------------------------------------------------------------
# BLOCK 1 -- paste after state / demag / external / filters are set up
# ----------------------------------------------------------------------------

# Phase filters: float indicator fields of shape [nx, ny, nz, 1], 1.0 inside
# the phase, 0.0 elsewhere. Must be disjoint and together cover ALL cells
# with Ms > 0. Example if you have an integer domain field
# (0 = matrix, 1 = large, 2 = small):
#
#     filter_L = state.Constant([0.]); filter_L[domains == 1] = 1.0
#     filter_S = state.Constant([0.]); filter_S[domains == 2] = 1.0

mu0 = constants.mu_0
phi_L = state.avg(filter_L)   # volume fraction of each powder in the mesh
phi_S = state.avg(filter_S)   # (logged as constants, used for normalisation)


def demag_h_partial(state, source_filter):
    """Demag field generated ONLY by the magnetisation inside source_filter.

    Exploits the linearity of the demag convolution in Ms*m: temporarily
    replacing state.m by the masked magnetisation and evaluating demag.h
    yields exactly the stray field of the source phase, everywhere on the
    mesh. Works with DemagField and DemagFieldPBC alike: both read Ms*m
    freshly on every call, and the cached demag tensor N depends only on
    the mesh, not on m. state.m has no special setter (no normalisation),
    so the swap/restore is safe as long as it happens OUTSIDE llg.step.
    Cost: one extra FFT convolution per call. Returns [nx,ny,nz,3] in A/m.
    """
    m_full = state.m
    try:
        state.m = m_full * source_filter   # keep only the source magnetisation
        return demag.h(state)
    finally:
        state.m = m_full                   # restore the original tensor object


# Logger columns (each vector column expands to _x/_y/_z in the file):
#   t             simulation time                                 [s]
#   h_ext         applied field                                   [A/m]
#   phi_L, phi_S  phase volume fractions (constants)              [1]
#   J_L,  J_S     mu0 * <M>_i, phase-averaged polarisation        [T]
#   hd_L, hd_S    <h_demag>_i, full demag field in phase i        [A/m]
#   hL_L          field of powder L averaged over powder L (self) [A/m]
#   hL_S          field of powder L averaged over powder S (cross)[A/m]
#   hS_L          field of powder S averaged over powder L (cross)[A/m]
#   hS_S          field of powder S averaged over powder S (self) [A/m]
#
# The lambdas only slice/average the fields attached to the state in the
# time loop (BLOCK 2), so each demag convolution runs exactly once per row.
logger = ScalarLogger("data/loop.dat", [
    't',
    ('h_ext', lambda s: external.h(s)),
    ('phi_L', lambda s: float(phi_L)),
    ('phi_S', lambda s: float(phi_S)),
    ('J_L',   lambda s: mu0 * s.material["Ms"] * s.m * filter_L / phi_L),
    ('J_S',   lambda s: mu0 * s.material["Ms"] * s.m * filter_S / phi_S),
    ('hd_L',  lambda s: s.h_demag  * filter_L / phi_L),
    ('hd_S',  lambda s: s.h_demag  * filter_S / phi_S),
    ('hL_L',  lambda s: s.h_from_L * filter_L / phi_L),
    ('hL_S',  lambda s: s.h_from_L * filter_S / phi_S),
    ('hS_L',  lambda s: s.h_from_S * filter_L / phi_L),
    ('hS_S',  lambda s: s.h_from_S * filter_S / phi_S),
])


# ----------------------------------------------------------------------------
# BLOCK 2 -- additions INSIDE your existing time loop
# ----------------------------------------------------------------------------
# Your loop probably looks like this; add the 4 marked lines AFTER llg.step:
#
#     for i in tqdm(torch.arange(0, T, dt)):
#         llg.step(state, dt)
#
#         state.h_demag  = demag.h(state)                    # 1 FFT conv   <<<
#         state.h_from_L = demag_h_partial(state, filter_L)  # 1 FFT conv   <<<
#         state.h_from_S = demag_h_partial(state, filter_S)  # 1 FFT conv   <<<
#         logger << state                                    #              <<<
#
# Notes:
# * The three extra convolutions per logged step are cheap compared to one
#   llg.step (which runs several demag evaluations internally). If that is
#   still too much, log only every Nth step -- then create the logger with
#   every=N AND guard the field updates with the same stride:
#
#         if i_step % N == 0:
#             state.h_demag  = demag.h(state)
#             state.h_from_L = demag_h_partial(state, filter_L)
#             state.h_from_S = demag_h_partial(state, filter_S)
#         logger << state          # must be called EVERY step for every=N
#
# * Cheaper alternative for the small powder, exact by linearity (use it
#   once the filters are validated, saves one FFT):
#
#         state.h_from_S = state.h_demag - state.h_from_L
#
#   Keeping the explicit version instead makes h_demag - h_from_L - h_from_S
#   a genuine filter consistency check (residual must be round-off only).
